version: '3'
services:
  saqr-db:
    image: postgres:9.5.12
    ports:
      - "5432:5432"
    volumes:
      - ~/SAQR/SAQR-DB:/var/lib/postgresql/data
    networks:
      - saqr_network

  saqr-api:
    build:
      context: ./SAQR-API
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - saqr-db
    networks:
      - saqr_network

  saqr-front:
    build:
      context: ./SAQR-FRONT
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    depends_on:
      - saqr-api
    networks:
      - saqr_network

networks:
  saqr_network:
    driver: bridge