version: '3'
services:
  saqr-db:
    image: postgres:9.5.12
    volumes:
      - ~/SAQR/SAQR-DB:/var/lib/postgresql/data

  saqr-api:
    image: saqr-api
    #    build:
    #      context: .
    #      dockerfile: ./SAQR-API/Dockerfile
    command: bash start.sh
    ports:
      - "3030:3030"
    depends_on:
      - saqr-db

  saqr-front:
    #    image: saqr-front
    build:
      context: .
      dockerfile: ./SAQR-FRONT/Dockerfile
    command: npm start
    ports:
      - "80:3000"
    depends_on:
      - saqr-api
